# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "635f9f7e155666e257380fe4b2254958"
name = "FreeShip-Rules"
embedded = true
application_url = "https://freeshiprules-production.up.railway.app"

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts"
use_legacy_install_flow = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://freeshiprules-production.up.railway.app/auth/callback" ]
